### ISSUE TITLE
Swiching between tasks

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#100]
For example I have 2 problems.  When I switched to code of second problem and try run clion will run the first problem.  I tried chelper its switching automatically.  Is it possible enable to jhelper also?

**Comment by AlexeyDmitriev** [comment]
Do you mean switching automatically when you open other file? That sounds good (but I don't remember CHelper doing that), I'll investigate how to do this.

**Comment by emli** [comment]
Yes, you are right.

Please try latest CHelper

**Comment by AlexeyDmitriev** [comment]
I've added auto switcher. It is in JHelper v0.16, which should be available in plugin repository in two business days. 
Thanks for a nice idea again.

**Comment by emli** [comment]
Updated, thank you for nice feature
