### ISSUE TITLE
In today contest test were parsed with additionally spaces 

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#101]
![image](https://user-images.githubusercontent.com/5517490/48675217-a1576280-eb80-11e8-9a51-e624284d5a80.png)

**Comment by AlexeyDmitriev** [comment]
Hi, what parser did you use? I tried with both Competitive companion and CHelper extension and couldn't reproduce. Does it still work incorrectly?

**Comment by emli** [comment]
@AlexeyDmitriev can you parse latest contest in codeforces (https://codeforces.com/contest/1061)

![image](https://user-images.githubusercontent.com/5517490/48963134-791f9780-efb6-11e8-8d11-87eedd56e7d6.png)


parse for problem is working but not working for contest for me.

**Comment by AlexeyDmitriev** [comment]
Yes, I get the same behaviour when parsing from inside IDE now, can you please try that in CHelper (I don't have an environment configured now) to see whether the problem is in parser itself or in JHelper integration. 

Thanks

**Comment by AlexeyDmitriev** [comment]
Meanwhile, I've found that parsing a contest using Competitive companion extension doesn't work correctly either (it returns the same testcase for all the problems). I'll investigate this.

**Comment by emli** [comment]
Tried with CHelper also. Problem is in extension

**Comment by AlexeyDmitriev** [comment]
Can you please file a bug there then?
