### ISSUE TITLE
How to use scanf and printf in Jhelper?

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#103]

**Comment by AlexeyDmitriev** [comment]
there's no adequate way I'm aware of and there's no plans to support it. With rewriting templates you may be able to make your own classes that supports both reading from files/stdin and strings (for local testing) or hack with FILE* but there's no and not going to be a direct way.

Note that if your concern is performance, then you should now that after adding two magic lines i/o with iostreams has the same performance as stdio. (Usually even a bit better). There are sometimes issues with windows toolchains, but on CF you may find reasonable compiler once(before update at least) and all other platforms I remember use adequate gcc on linux toolchains.
