### ISSUE TITLE
Having function instead of class causes tests to be invalid

### ISSUE THREAD

**Issue by mehranagh20** [AlexeyDmitriev/JHelper#109]
I've changed the _task, submission and template_ files so I can have a function instead of class.

It compiles and works but because of global static arrays and variables which are initialized to 0 for the first test but later for other tests they are changed and affected by previous tests result of tests changes.

How can I have a fresh start for each test and avoid having classes?

**Comment by mehranagh20** [comment]
@AlexeyDmitriev Do you have any solution for this problem? :)

**Comment by AlexeyDmitriev** [comment]
@mehranagh20 Sorry for late answer.

I do not have solution for this except using local variables (and pass them to other functions and/or capture them by lambdas). Note, that static and global variables still will not work even with classes (but you may use fields). 
You may find relevant discussion in #97

**Comment by AlexeyDmitriev** [comment]
Please let me know if you have other questions/comments on that

**Comment by mehranagh20** [comment]
@AlexeyDmitriev Thanks for your response.
Do you think is it somehow possible to re-execute the code for each test?

**Comment by AlexeyDmitriev** [comment]
I'm not sure I understand the question.
