### ISSUE TITLE
Add support for CLion 2019.2

### ISSUE THREAD

**Issue by dodomarocgenex** [AlexeyDmitriev/JHelper#114]
The current plugin can't parse AtCoder tasks with CLion 2019.2. 
Please add the corresponding compatibility

Configuration: 
OS: Mac os Catalina
JHelper version: 0.16.2

**Comment by AlexeyDmitriev** [comment]
Hi, dodomarocgenex

Thanks for the feedback. Can you clarify which parser you are using?
I recommend you use competitive-companion

сб, 26 окт. 2019 г. в 17:53, dodomarocgenex <notifications@github.com>:

**Comment by dodomarocgenex** [comment]
I was using CHelper, which worked on Codeforces. 
But with Competitive Companion, it works just fine on both AtCoder and Codeforces.

Thanks!
