### ISSUE TITLE
Cannot parse task from codeforces on 2020.1 clion

### ISSUE THREAD

**Issue by rishabhdeepsingh** [AlexeyDmitriev/JHelper#117]
I am getting the following error on CLion 2020.1 after today I updated it is showing the following error on codeforces `Maybe format changed?`

**Comment by AlexeyDmitriev** [comment]
What parser do you use? 
I was able to parse random problem with Chelper chrome extension (but not competitive companion)
Are you sure that the problem doesn't reproduce with older CLion? (Don't have time to check at the moment)

**Comment by AlexeyDmitriev** [comment]
It looks like indeed competitive companion is currently broken for Codeforces in Chrome (https://github.com/jmerle/competitive-companion/issues/83)

**Comment by rishabhdeepsingh** [comment]
Yes I am also using "Competitive Companion"
