### ISSUE TITLE
"ChromeParser: Got response without body. Ignore." notifications

### ISSUE THREAD

**Issue by GoBigorGoHome** [AlexeyDmitriev/JHelper#118]
I occasionally saw "ChromeParser: Got response without body. Ignore." message in CLion's Event Log after adding a task through Competitive Companion while there seems nothing wrong. What does that message mean and how to avoid them?

![event_log](https://user-images.githubusercontent.com/9896288/80348134-e7e5dc00-889f-11ea-847c-bbc433afb37f.png)

**Comment by AlexeyDmitriev** [comment]
CHelper plugin and competitive companoin plugin work in the following way:
1) HTTP server is created on localhost
2) When you click plus button, your browser connects to this HTTP server and sends description of the problem

So, probably either one of the plugins is sending incorrect request or something else is connected to this server. Are you trying to parse some problem at this moment? 
You can try to investigate further by changing code here https://github.com/AlexeyDmitriev/JHelper/blob/afab6a92e32b0884287a13a1a7d666864ef7e32c/src/name/admitriev/jhelper/network/SimpleHttpServer.java#L36

**Comment by GoBigorGoHome** [comment]
I just tried to add another task from AtCoder. The same message pops again a few (about 10) seconds after the I click the plus button on the web page and the task added. I have little experience in Java and JetBrains plugin, so I'm afraid there is not much I can do at the moment.

**Comment by AlexeyDmitriev** [comment]
So you are saying that tasked was added just fine?

**Comment by GoBigorGoHome** [comment]
Yes.

**Comment by AlexeyDmitriev** [comment]
Hmm, that's interesting. I'll try to reproduce when I have time. Can you send me the link to the problem which you parsed and let me know which of the extensions have you used? (Competitive companion or CHelper)

**Comment by GoBigorGoHome** [comment]
I use Competitive companion on Chrome. Try parse this problem https://atcoder.jp/contests/abc164/tasks/abc164_f. I can provide a sample of my CLion project if needed. I use JHelper 0.16.3 and CLion 2020.1.

**Comment by AlexeyDmitriev** [comment]
No, the project won't be needed, thanks.

**Comment by AlexeyDmitriev** [comment]
I couldn't reproduce that, I guess something else is trying to connect to your open port. I decided to allow only localhost connections just in case. Change is in master 4697dc230c56f56d6a65a2ecf3d0f1 and will be published in the next version along with next changes
