### ISSUE TITLE
Custom templates for code generation

### ISSUE THREAD

**Issue by rishabhdeepsingh** [AlexeyDmitriev/JHelper#128]
Is there a way we can add custom templates to generate the `main.cpp` file.

**Comment by AlexeyDmitriev** [comment]
What is main.cpp?

**Comment by rishabhdeepsingh** [comment]
The output file

**Comment by AlexeyDmitriev** [comment]
Yes, it's called submission.template

**Comment by rishabhdeepsingh** [comment]
I just want to remove the `void solve(std::istream& cin, std::ostream& cout)` can't we use the global IO or write a custom IO just like [Egor's CPP](https://github.com/EgorKulikov/cpp/blob/master/lib/io/input.h) or the simple `cin` or `cout` without passing the `istream` to every function we want to perform.

**Comment by AlexeyDmitriev** [comment]
This can't be done using templates
I said you already that Egor patched Jhelper
