### ISSUE TITLE
Is it possible to treat some library files as "standard library" and not inline them?

### ISSUE THREAD

**Issue by GoBigorGoHome** [AlexeyDmitriev/JHelper#130]
Some OJs, e.g. AtCoder, provides libraries, is it possible for JHelper not to inline them, but treat them as if they were "standard library"?

**Comment by AlexeyDmitriev** [comment]
[Here](https://github.com/AlexeyDmitriev/JHelper/blob/231a778f7141708e9e3797e8a0b5e4a17975e795/src/name/admitriev/jhelper/generation/IncludesProcessor.java#L31) is the 
 check to determine whether to inline specific file (and its implementation on line 48), so my understanding is that if you just place the files of this library outside of the project, it should ignore the file (the same way it works with standard library).

Please let me know whether it works

**Comment by AlexeyDmitriev** [comment]
Hi, @GoBigorGoHome can you confirm whether it worked for you?

**Comment by GoBigorGoHome** [comment]
@AlexeyDmitriev Sorry for delay. Your understanding is mostly right. In fact, as the [function](https://github.com/AlexeyDmitriev/JHelper/blob/231a778f7141708e9e3797e8a0b5e4a17975e795/src/name/admitriev/jhelper/generation/IncludesProcessor.java#L50) name `isInProjectSources` indicates, only those include files that are in project sources are inlined. As far as I know, only those files that are listed as source files of some target in CMakeLists.txt or those files in directories marked as "Project Sources and Headers" are considered "InProjectSources".

So, if a library should be inlined, then put it inside the project directory and mark it as "Project Sources and Headers". If the library should not be inlined, just do not mark, it does not matter whether the library is inside the project or not.

![marked as Project sources](https://user-images.githubusercontent.com/9896288/99369383-569b8d00-28f7-11eb-90ad-2000cc5eac27.png)
