### ISSUE TITLE
Exception while parsing tasks of a contest

### ISSUE THREAD

**Issue by Dhruv-Rana** [AlexeyDmitriev/JHelper#133]
When I try to parse tasks from [here](https://codeforces.com/contest/1552), after parsing 3-4 tasks I am facing this:

java.lang.NullPointerException
	at name.admitriev.jhelper.ui.Notificator.showNotification(Notificator.java:14)
	at name.admitriev.jhelper.network.SimpleHttpServer.run(SimpleHttpServer.java:45)
	at java.base/java.lang.Thread.run(Thread.java:829)

I am using CLion 2021.1.3

**Comment by Dhruv-Rana** [comment]
this seems to be some issue with new version of CLion

**Comment by AlexeyDmitriev** [comment]
Does it trigger if you parse tasks 1 by 1? IIUC this only triggers only on attempt to report some other problem.
I'll look into this if I have time anyway, but as a workaround it might help.

**Comment by Dhruv-Rana** [comment]
Yes it's triggering even when I parse tasks one-by-one. Thanks!

**Comment by AlexeyDmitriev** [comment]
On every problem?

**Comment by Dhruv-Rana** [comment]
No, it's triggering very randomly. Sometimes after parsing a single task, sometimes after parsing 3/4 tasks. Once triggered, I cannot parse any further tasks.

**Comment by AlexeyDmitriev** [comment]
The exception should be fixed by #134 in v0.19.1
Please let me know  whether it is fixed for you

**Comment by Dhruv-Rana** [comment]
Yes the issue is fixed now. Thank you so much!

**Comment by AlexeyDmitriev** [comment]
Well, thanks to @AntKirill . I actually forgot to look into that
