### ISSUE TITLE
Add Saratov State University olimp problems archive

### ISSUE THREAD

**Issue by solomax2014** [AlexeyDmitriev/JHelper#88]
Can you add support for acm.sgu.ru/olimp ?

**Comment by AlexeyDmitriev** [comment]
Hi,

There's currently no plans for acm.sgu.ru since I don't use it, but I'll be happy to apply your patches if you are willing to add it.

**Comment by AlexeyDmitriev** [comment]
Well, I think it's now closed (and problems are available on CF), so that doesn't make much of a sense.
