### ISSUE TITLE
Not working on newest version CLion 2017 1.3

### ISSUE THREAD

**Issue by qfu** [AlexeyDmitriev/JHelper#90]
I imported the example project and installed the JHelper but it prompted out errors: PSI not found..

**Comment by AlexeyDmitriev** [comment]
Sorry for late response.

There was a problem with example project (it was not updated for changes in JHelper 0.13).

Could you please try with updated example project?

**Comment by qfu** [comment]
Thanks for the update, everything works fine now.

**Comment by AlexeyDmitriev** [comment]
cool
