### ISSUE TITLE
Speed of compiling

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#98]
Sometimes it's too slow speed of compilation. How to solve this problem? I tried Power Save Mode  but it didn't help well

**Comment by AlexeyDmitriev** [comment]
Well, Power Safe Mode is probably would only make it worse.

Is compilation slow for you only with JHelper? What if you compile target testrunner directly inside or outside an IDE? (`make testrunner` in cmake-build-debug directory).

**Comment by emli** [comment]
> Is compilation slow for you only with JHelper? 

I think yes, I used clion without jhelper - it was working pretty good. 

> What if you compile target testrunner directly inside or outside an IDE? (make testrunner in cmake-build-debug directory).

It's also litte slow

**Comment by emli** [comment]
![image](https://user-images.githubusercontent.com/5517490/47854208-611b8480-de0b-11e8-909f-b7221abb442b.png)

**Comment by emli** [comment]
https://github.com/emli/competitive/blob/master/tasks/cf/CDivideByThree.cpp

Here you can see some codes
