### ISSUE TITLE
Support TopCoder

### ISSUE THREAD

**Issue by emli** [AlexeyDmitriev/JHelper#99]
Maybe this issue duplicated. 

But it would be nice have topcoder support. When we can see this feature ? I think there many coders will happy to see this feature.  Also memnbers of topcoder will happy to see this feature.

**Comment by emli** [comment]
Additionally it would be nice to submit every task directly from jhelper

**Comment by AlexeyDmitriev** [comment]
Well, I was going to support TopCoder before (and created an issue for that (#14)), and it is certainly will be nice feature to have, but I don't think I'll ever do that, because I almost do not participate in topcoder now.

I'll be glad to review a PR if somebody is interested to implement this.
